name: Laravel CI

on:
  push:
    branches: [ main ]

jobs:
  laravel-test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Copy ENV
        run: cp .env.example .env

      - name: Generate Key
        run: php artisan key:generate

      - name: Run Tests
        run: php artisan test
